name: SpaceandShells
favicon: null
layout_spectrum: 0.6571
typography_spectrum: 0.20321
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#98917e'
    - '#070705'
    - '#9c0400'
    - '#9af5ff'
    - '#a23900'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
