name: SpaceandShells
favicon: null
layout_spectrum: 0.6571
typography_spectrum: 0.20321
title: Space and Shells
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75618963-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#020202'
    - '#5faef0'
    - '#763765'
    - '#fa6e54'
  brandStrength: 0.0625
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
