name: SpaceandShells
favicon: null
layout_spectrum: 0.6571
typography_spectrum: 0.20321
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9cb4d3'
    - '#182f59'
    - '#385173'
    - '#7f7f7f'
    - '#d6d6d6'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
